### ISSUE TITLE
pretty_segments_df.pkl

### ISSUE THREAD

**Issue by ziyang773** [uwmisl/PASTOR-sequencing#2]
Excuse me for bothering again, but is this file "pretty_segments_df.pkl" in humpsClassifier.py, line 16 also missing? Thanks!

**Comment by daphkh** [comment]
No worries -- I'm thrilled you're trying to use this stuff! Also feel free to reach out to me at [my github username]@uw.edu if you ever have questions.

That one was another mistake on my end -- I changed the .pkl files to .json files because .pkl files sometimes present version issues, but I failed to update all the references.
